import type { MiniGamePracticeBriefing } from '../../app/gameplaySessionContract';

export interface LearnerGuide extends MiniGamePracticeBriefing { example: string; revisionKey: string; }
const guide = (title: string, summary: string, bullets: string[], example: string, revisionKey = ''): LearnerGuide => ({ title, summary, bullets, example, revisionKey });

/** Learner-facing instructions describe the actual controls, then the maths. */
export const LEARNER_GUIDES: Record<string, LearnerGuide> = {
  place_value_panic: guide('Place Value Panic', 'Build the number shown in the mission.', ['Read each place from left to right: millions, thousands, hundreds, tens, ones, then decimal places.', 'Tap a digit to fill the next space, or drag it to its labelled place. Tap a filled space to remove it.', 'Check that the digits make the whole target number before submitting.'], 'In 4,206, the 2 means 200. In 4.206, the 2 means two tenths.', 'place_value_panic'),
  number_line_ninja: guide('Number Line Ninja', 'Find the number or distance on the number line.', ['Read two neighbouring labelled marks. Divide their difference by the number of equal gaps.', 'Count the gaps to the target. Numbers to the left of zero are negative.', 'Choose the answer that matches the mission, rather than just the nearest label.'], 'From −3 to 2 is 5 steps: 3 to reach zero, then 2 more.', 'number_line_ninja'),
  prime_pop: guide('Prime Pop', 'Pop the prime-number bubbles before they cross the line.', ['A prime has exactly two factors: 1 and itself. The number 1 is not prime.', 'Read each bubble. Test whether a number other than 1 and itself divides it exactly.', 'Tap prime bubbles to pop them. Leave non-primes alone: tapping them costs a life in scored levels.'], '7 is prime. 9 is not, because 3 × 3 = 9.', 'prime_pop'),
  rounding_rocket: guide('Rounding Rocket', 'Round the number to the place named in the mission.', ['Find the digit in the requested place.', 'Look one place to its right: 0–4 keeps it the same; 5–9 rounds it up.', 'Replace later whole-number digits with zeros, or remove later decimal digits. Choose the result.'], '3,650 rounded to the nearest hundred is 3,700.', 'rounding_rocket'),
  maths_vs_zombies: guide('Maths vs Zombies', 'Solve the calculation to push the zombies back.', ['Read the operation: + adds, − subtracts, × multiplies and ÷ divides.', 'Work out the answer. Use number facts or split a large number into smaller parts.', 'Choose your answer to attack. For division, check by multiplying back.'], '18 ÷ 3 = 6 because 6 × 3 = 18.', 'maths_vs_zombies'),
  take_out_rush: guide('Take-Out Rush', 'Build the café order so the portion values add to the target.', ['Read the target fraction and any order rules, such as a required ingredient or item limit.', 'Tap foods to add their labelled fractions to the tray. Use equal denominators to add different-sized portions.', 'Tap a tray item to remove it. Match the target exactly and obey every order rule before serving.'], 'For a target of 3/4, a 1/2 portion plus a 1/4 portion works: 2/4 + 1/4 = 3/4.', 'take_out_rush'),
  fraction_forge: guide('Fraction Forge', 'Combine fraction ingredients to make the target.', ['Read the target fraction and the + or − signs between the forge slots.', 'Tap ingredients to fill the slots from left to right. Tap a filled slot to return its ingredient to the bank.', 'Make the denominators match before adding or subtracting. Press Strike when your result equals the target.'], 'To make 5/6, use 1/2 + 1/3: 3/6 + 2/6 = 5/6.', 'fraction_forge'),
  match3_equivalence: guide('Match Mastery', 'Swap tiles to line up three equal values.', ['In levels 1–2, match equivalent fractions by multiplying or dividing the top and bottom by the same number.', 'From level 3, fractions, decimals and percentages can all show the same value. Swap neighbouring tiles to make a row or column of three.', 'In level 5, the tiles have no colour clue. Read the values to find a match.'], '1/2, 0.5 and 50% all mean the same amount.', 'match3_equivalence'),
  percent_power: guide('Percent Power', 'Find the missing amount to power the reactor.', ['Read whether you need a percentage of an amount, or the original whole.', 'Find useful pieces: 10% is divide by 10; 1% is divide by 100; 50% is half.', 'Combine those pieces and choose the answer. If finding the whole, work backwards.'], '15% of 80 = 10% (8) + 5% (4) = 12. If 25% is 12, the whole is 48.', 'percent_power'),
  simplify_sprint: guide('Simplify Sprint', 'Race through the gates by reducing each fraction to its simplest form.', ['Read the fraction, then choose a gate marked ÷ by a number that divides both the top and bottom exactly.', 'Each safe gate divides both numbers. If the fraction can still be reduced, choose another safe gate.', 'Reach a fraction with no shared factor greater than 1 to clear the stage. In scored levels, avoid wrong gates and keep your streak going.'], '12/18 can use ÷ 2 to make 6/9, then ÷ 3 to make 2/3.', 'simplify_sprint'),
  angle_arena: guide('Angle Arena', 'Work out the missing angle, then aim the cannon.', ['Read the angle labels and the shape in the mission.', 'Angles on a straight line total 180°. Around a point they total 360°. A triangle totals 180°.', 'Subtract the known angles from the total. Choose that angle and fire.'], 'A triangle with 50° and 60° needs 70°: 180 − 50 − 60 = 70.', 'angle_arena'),
  polygon_palace: guide('Polygon Palace', 'Choose the shapes that match the description.', ['Read the property requested. There may be more than one correct shape.', 'For flat shapes, count sides and angles. For solids, count faces, edges and vertices (corners).', 'Select every matching shape, then confirm. Look for equal sides, parallel sides or symmetry when asked.'], 'A cube has 6 square faces, 12 edges and 8 vertices.', 'polygon_palace'),
  area_architect: guide('Area Architect', 'Find the space inside the shape.', ['Read the labelled lengths. Area is inside a shape; perimeter goes around it.', 'For a rectangle, multiply length by width. For a triangle, halve base × height.', 'Split a compound shape into rectangles, add their areas and choose the result. Use square units.'], 'A 6 cm by 4 cm rectangle has area 24 cm².', 'area_architect'),
  rotation_relay: guide('Rotation Station', 'Move the shape to match the target.', ['Read the movement requested: rotate (turn), reflect (mirror), or translate (slide).', 'Use the turn or flip controls. For a rotation, check the direction and angle.', 'Match every corner to the target before checking. A reflection reverses the shape.'], 'A quarter turn is 90°. A half turn is 180°.', 'rotation_relay'),
  coordinates_quest: guide('Coordinates Quest', 'Use coordinates to move across the map.', ['Read coordinates as (x, y): across first, then up or down.', 'Start at (0, 0). Negative x goes left; negative y goes down.', 'Find the requested point on the grid and choose it. Read both coordinates before moving.'], '(−2, 3) means 2 left and 3 up from the origin.', 'coordinates_quest'),
  conversion_canyon: guide('Conversion Canyon', 'Load the scale with the same weight as the target.', ['Convert all weights to the same unit: 1 kg = 1,000 g.', 'Tap weights to place them on the tray. Tap a selected weight again to remove it.', 'Add the selected weights and submit when they equal the target. If overloaded, remove the excess shown.'], '1.25 kg = 1,250 g. Two 500 g weights and one 250 g weight balance it.', 'conversion_canyon'),
  perimeter_path: guide('Perimeter Path', 'Find the total distance around the shape.', ['Tap each side to mark that you have read its length.', 'Add every outside edge once. Work out any missing side from the matching opposite lengths.', 'Choose the total in the same length unit. Do not multiply length by width: that finds area.'], 'A 6 cm by 4 cm rectangle has perimeter 6 + 4 + 6 + 4 = 20 cm.', 'perimeter_path'),
  mean_machine: guide('Mean Machine', 'Scan the numbers, then calculate the statistic requested.', ['Press Scan to reveal the numbers. Read whether the mission asks for mean, median, mode or range.', 'Mean: add and divide by the count. Median: sort and find the middle. Mode: most frequent. Range: largest minus smallest.', 'Choose your answer to repair the machine. For two middle numbers, their average is the median.'], 'For 2, 4, 4, 6: mean = 16 ÷ 4 = 4; median = 4; mode = 4; range = 4.', 'mean_machine'),
  graph_grabber: guide('Graph Grabber', 'Use the graph to answer the mission.', ['Read the title, axis labels and units. Check what one interval on the scale represents.', 'Find the named bar or point and read its value from the scale.', 'If asked for a difference, subtract; for a total, add. Choose the result.'], 'A bar at 30 and a bar at 18 differ by 12, not 48.', 'graph_grabber'),
  line_graph_lab: guide('Line Graph Lab', 'Read how a value changes over time.', ['Read both axes and count the value of each interval.', 'Follow the requested time up to the line, then across to the value axis.', 'Compare points for change. For a time between points, read along the joining line.'], 'Temperature rising from 8°C to 14°C increases by 6°C.', 'line_graph_lab'),
  data_detective: guide('Data Detective', 'Match the evidence to one suspect.', ['Read the clue. Use the chart labels and scale to find the required totals.', 'Open suspect dossiers and compare each one with every clue. Pin a clue to keep it in view.', 'Choose the suspect who matches all the evidence, then accuse. One matching clue is not enough.'], 'If the clue says 12 red and twice as many blue, you need 12 red and 24 blue.', 'data_detective'),
  calculation_clash: guide('Calculation Clash', 'Solve the calculation or missing-number mission.', ['Read the whole number sentence, including any brackets.', 'Use place value for large sums. Keep ones under ones and decimal points lined up.', 'Check using the opposite operation, then choose the answer.'], 'For □ + 37 = 100, subtract: 100 − 37 = 63.', 'calculation_clash'),
  factor_frenzy: guide('Factor Frenzy', 'Find the numbers that divide the target exactly.', ['Read whether the mission asks for a factor, multiple or common factor.', 'Factors divide exactly. Multiples come from the times table. Common factors divide both numbers.', 'Select the matching numbers and check that no remainder is left.'], 'Factors of 12 are 1, 2, 3, 4, 6 and 12. A common factor of 12 and 18 is 6.', 'factor_frenzy'),
  multiplication_mine: guide('Multiplication Mine', 'Solve each multiplication to break through the rock.', ['Read the two factors in the mission.', 'Split a large factor into tens and ones. Multiply each part, then add the products.', 'Choose the result. For two-digit multiplication, remember the tens row represents tens.'], '23 × 14 = 23 × 10 + 23 × 4 = 230 + 92 = 322.', 'multiplication_mine'),
  order_ops_arena: guide('Order Ops Arena', 'Solve the calculation in the correct order.', ['Work out brackets first, then powers if there are any.', 'Do multiplication and division next, from left to right.', 'Do addition and subtraction last, from left to right. Choose the final value.'], '18 − 3 × 4 = 18 − 12 = 6. For 24 ÷ 4 × 2, work left to right: 6 × 2 = 12.', 'order_ops_arena'),
  formula_forge: guide('Formula Forge', 'Use the rule to find a missing number.', ['Read what each letter stands for and the rule given.', 'Replace the letters with the known numbers. Follow the normal order of operations.', 'If a value is missing, undo the operations to find it. Choose the value that makes the rule true.'], 'If y = 3x + 2 and x = 4, y = 12 + 2 = 14.', 'formula_forge'),
  remainder_run: guide('Remainder Run', 'Divide and decide what to do with what is left.', ['Find how many full groups of the divisor fit into the number.', 'Subtract the amount used to find the remainder. It must be smaller than the divisor.', 'Read the mission: give a remainder, a decimal or round up for enough whole containers. Choose the matching form.'], '17 ÷ 5 = 3 remainder 2. To carry 17 people in cars holding 5, you need 4 cars.', 'remainder_run'),
  time_keeper_cove: guide('Chrono Dash', 'Set the clock to the requested time.', ['Read the hours and minutes. The short hand shows hours; the long hand shows minutes.', 'Use the hour and minute controls to move the hands. Each big number on the clock represents 5 minutes.', 'Match the mission and confirm. For durations, count to the next hour and then add the remaining minutes.'], '09:45 to 10:20 lasts 15 + 20 = 35 minutes.', 'time_keeper_cove'),
  problem_pyramid: guide('Problem Pyramid', 'Solve the word problem one step at a time.', ['Read what you must find. Pick out the useful numbers and their units.', 'Choose the first operation, calculate it, then use that result for the next step.', 'Check that the final answer makes sense in the story and choose it.'], 'Three tickets cost £4 each. Paying £20 leaves £20 − (3 × £4) = £8.', 'problem_pyramid'),
  unit_mixer: guide('Lava Path', 'Convert the units to stabilise each stepping stone.', ['Read the starting unit and the unit you need.', 'Going to smaller units multiplies; going to larger units divides. Use 100 cm = 1 m, 1,000 m = 1 km, 1,000 ml = 1 litre.', 'Choose the converted amount to cross. Keep the value of the quantity the same.'], '2.4 m = 240 cm. 750 ml = 0.75 litres.', 'unit_mixer'),
  change_counter: guide('Change Counter', 'Give the customer exactly the right change.', ['Add the prices to find the total bill.', 'Subtract the bill from the amount paid. Work in pence if decimals are tricky.', 'Tap coins to build that change, then submit. Tap a chosen coin to remove it if needed.'], 'Paid £5 for a £3.65 order: 500p − 365p = 135p = £1.35.', 'change_counter'),
  potion_panic: guide('Potion Panic', 'Mix ingredients in the ratio shown.', ['Read how many parts belong to each ingredient.', 'Find the size of one part, then multiply it by each ingredient’s number of parts.', 'Use the ingredient controls to build the mix and check it. Keep the same ratio when making a larger batch.'], 'A 2:3 mix with 20 ml total has 5 parts. Each is 4 ml, so use 8 ml and 12 ml.', 'potion_panic'),
  share_splitter: guide('Share Splitter', 'Share the cake in the amounts requested.', ['Read how many slices there are and the share each plate needs.', 'Divide by the total number of parts to find one part; multiply for each plate’s share.', 'Drag slices to plates, or tap the cake then a plate. Check when every share is correct.'], 'Share 20 slices in a 2:3 ratio: 20 ÷ 5 = 4 per part, so 8 and 12 slices.', 'share_splitter'),
  ratio_fractions: guide('Ratio Racer', 'Use ratios and fractions to move along the track.', ['Read the ratio and what the question asks for.', 'For a fraction of the whole, add the ratio parts for the denominator. For a missing amount, find the scale factor.', 'Choose the answer. Accurate answers move the car forward along the course.'], 'In red:blue = 2:3, red is 2/5 of all cars, not 2/3.', 'ratio_fractions'),
  scale_builder: guide('Scale Builder', 'Resize the model using its scale factor.', ['Read the original lengths and the scale factor.', 'Multiply every length by that factor. If finding the original, divide instead.', 'Use the size controls to match the target and check. All lengths must use the same factor.'], 'At scale factor 3, a 4 cm by 2 cm shape becomes 12 cm by 6 cm.', 'scale_builder'),
};
for (const key of ['crystal_core', 'mirror_gate', 'matrix_match']) {
  LEARNER_GUIDES[key] = guide('Core of Calculation', 'Complete a timed adventure using the maths you have practised.', ['Save an answer to charge a mission crystal. You can change it before finishing.', 'Use Later for a difficult mission. Open the mission list to return to saved or unanswered missions.', 'Finish the run when ready, or when time ends. Then review the solutions and revisit the suggested minigames.'], 'Use paper for working out. No calculator. Help explains the controls during a mock; solutions appear only after it ends.');
}
export const getLearnerGuide = (key?: string | null) => key ? LEARNER_GUIDES[key] ?? null : null;
