// Auto-generated Angle Arena question bank for SATs Legends
export type AngleQuestion = {
  id: number;
  prompt: string;
  options: number[];
  correctAnswer: number;
  targetX: number;
  targetY: number;
  launchSpeed: number;
  explanation: string;
  difficulty: 'Easy' | 'Mild' | 'Medium' | 'Hard' | 'Expert';
  topic: string;
  diagramDescription: string;
  wrongAnswerRationale: Record<string, string>;
  accessibilityText: string;
};

type BuildConfig = {
  launcherX: number;
  groundY: number;
  gravity: number;
};

type BankEntry = {
  id: string;
  difficulty: AngleQuestion['difficulty'];
  topic: string;
  question_text: string;
  diagram_description: string;
  options: string[];
  correct_answer: string;
  explanation: string;
  wrong_answer_rationale: Record<string, string>;
  accessibility_text: string;
};

const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value));

const parseAngle = (value: string) => Number(value.replace('Â°', '').trim());

const buildTarget = (launcherX: number, angleDeg: number, speed: number, gravity: number) => {
  const radians = (angleDeg * Math.PI) / 180;
  const range = (speed * speed * Math.sin(2 * radians)) / gravity;
  const targetX = clamp(launcherX + range * 0.9, launcherX + 320, launcherX + 1400);
  return targetX;
};

const toAngleQuestion = (
  entry: BankEntry,
  index: number,
  speed: number,
  launcherX: number,
  groundY: number,
  gravity: number,
  targetHeight = 54,
): AngleQuestion => {
  const correct = parseAngle(entry.correct_answer);
  const options = entry.options.map(parseAngle);
  const targetX = buildTarget(launcherX, correct, speed, gravity);
  const targetY = groundY - targetHeight;
  return {
    id: index + 1,
    prompt: entry.question_text,
    options,
    correctAnswer: correct,
    targetX,
    targetY,
    launchSpeed: speed,
    explanation: entry.explanation,
    difficulty: entry.difficulty,
    topic: entry.topic,
    diagramDescription: entry.diagram_description,
    wrongAnswerRationale: entry.wrong_answer_rationale,
    accessibilityText: entry.accessibility_text,
  };
};

const questionBank: BankEntry[] = [
  {
    id: 'Q1',
    difficulty: 'Easy',
    topic: 'right_angles',
    question_text: 'How many degrees is a right angle?',
    diagram_description: 'A square corner labelled as a right angle.',
    options: ['45Â°', '60Â°', '90Â°', '120Â°'],
    correct_answer: '90Â°',
    explanation: 'A right angle measures 90 degrees.',
    wrong_answer_rationale: {
      '45Â°': 'Confused with half a right angle.',
      '60Â°': 'Mixed up with common triangle angles.',
      '120Â°': 'Confused with an obtuse angle.',
    },
    accessibility_text: 'Right angle shown as a square corner.',
  },
  {
    id: 'Q2',
    difficulty: 'Easy',
    topic: 'straight_line',
    question_text: 'How many degrees are on a straight line?',
    diagram_description: 'A straight line with a half-turn arrow.',
    options: ['90Â°', '180Â°', '270Â°', '360Â°'],
    correct_answer: '180Â°',
    explanation: 'Angles on a straight line add up to 180 degrees.',
    wrong_answer_rationale: {
      '90Â°': 'Confused with a right angle.',
      '270Â°': 'Confused with three-quarter turn.',
      '360Â°': 'Confused with a full turn.',
    },
    accessibility_text: 'Straight line with a half-turn arrow.',
  },
  {
    id: 'Q3',
    difficulty: 'Easy',
    topic: 'around_point',
    question_text: 'How many degrees are in a full turn?',
    diagram_description: 'A point with a full circular arrow.',
    options: ['180Â°', '270Â°', '360Â°', '450Â°'],
    correct_answer: '360Â°',
    explanation: 'A full turn is 360 degrees.',
    wrong_answer_rationale: {
      '180Â°': 'Half a turn.',
      '270Â°': 'Three-quarter turn.',
      '450Â°': 'Went beyond a full turn.',
    },
    accessibility_text: 'Full circular arrow around a point.',
  },
  {
    id: 'Q4',
    difficulty: 'Easy',
    topic: 'triangle_angles',
    question_text: 'A triangle has angles 50Â° and 60Â°. What is the third angle?',
    diagram_description: 'Triangle with two angles labelled 50Â° and 60Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '70Â°',
    explanation: 'Angles in a triangle add to 180Â°. 180 - 50 - 60 = 70.',
    wrong_answer_rationale: {
      '60Â°': 'Assumed equilateral.',
      '80Â°': 'Subtracted only one given angle.',
      '90Â°': 'Guessed a right angle.',
    },
    accessibility_text: 'Triangle with 50 degrees and 60 degrees marked.',
  },
  {
    id: 'Q5',
    difficulty: 'Easy',
    topic: 'isosceles',
    question_text: 'An isosceles triangle has two equal angles of 40Â°. What is the third angle?',
    diagram_description: 'Isosceles triangle with two equal angles labelled 40Â°.',
    options: ['40Â°', '80Â°', '100Â°', '120Â°'],
    correct_answer: '100Â°',
    explanation: 'Two angles are 40Â° each. 180 - 80 = 100Â°.',
    wrong_answer_rationale: {
      '40Â°': 'Assumed all three angles equal.',
      '80Â°': 'Added instead of subtracting from 180.',
      '120Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Isosceles triangle with two equal 40 degree angles.',
  },
  {
    id: 'Q6',
    difficulty: 'Easy',
    topic: 'straight_line',
    question_text: 'Two angles on a straight line are 110Â° and ___. What is the missing angle?',
    diagram_description: 'Straight line split into two angles, one labelled 110Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '70Â°',
    explanation: 'Angles on a straight line total 180Â°. 180 - 110 = 70.',
    wrong_answer_rationale: {
      '60Â°': 'Subtracted from 170 instead of 180.',
      '80Â°': 'Subtracted incorrectly.',
      '90Â°': 'Guessed a right angle.',
    },
    accessibility_text: 'Straight line with one angle labelled 110 degrees.',
  },
  {
    id: 'Q7',
    difficulty: 'Easy',
    topic: 'around_point',
    question_text: 'Angles around a point total 360Â°. If one angle is 200Â°, what is the other?',
    diagram_description: 'Two angles around a point, one labelled 200Â°.',
    options: ['120Â°', '140Â°', '160Â°', '180Â°'],
    correct_answer: '160Â°',
    explanation: 'Angles around a point add to 360Â°. 360 - 200 = 160.',
    wrong_answer_rationale: {
      '120Â°': 'Subtracted from 320 instead of 360.',
      '140Â°': 'Subtracted incorrectly.',
      '180Â°': 'Confused with a straight line.',
    },
    accessibility_text: 'Two angles around a point with one labelled 200 degrees.',
  },
  {
    id: 'Q8',
    difficulty: 'Easy',
    topic: 'quadrilateral',
    question_text: 'A rectangle has one angle marked. What is its size?',
    diagram_description: 'Rectangle with one corner highlighted.',
    options: ['45Â°', '60Â°', '90Â°', '120Â°'],
    correct_answer: '90Â°',
    explanation: 'All angles in a rectangle are right angles.',
    wrong_answer_rationale: {
      '45Â°': 'Confused with diagonal angle.',
      '60Â°': 'Mixed up with triangle angles.',
      '120Â°': 'Confused with obtuse angle.',
    },
    accessibility_text: 'Rectangle with one corner highlighted.',
  },
  {
    id: 'Q9',
    difficulty: 'Easy',
    topic: 'turns',
    question_text: 'A quarter turn is the same as how many degrees?',
    diagram_description: 'Arrow showing a quarter turn.',
    options: ['45Â°', '90Â°', '180Â°', '270Â°'],
    correct_answer: '90Â°',
    explanation: 'A quarter turn is 90 degrees.',
    wrong_answer_rationale: {
      '45Â°': 'Half of a right angle.',
      '180Â°': 'A half turn.',
      '270Â°': 'Three-quarter turn.',
    },
    accessibility_text: 'Arrow turning one quarter of a circle.',
  },
  {
    id: 'Q10',
    difficulty: 'Easy',
    topic: 'vertically_opposite',
    question_text: 'Two vertically opposite angles are formed. One is 65Â°. What is the other?',
    diagram_description: 'Two crossing lines with one angle labelled 65Â°.',
    options: ['65Â°', '85Â°', '115Â°', '125Â°'],
    correct_answer: '65Â°',
    explanation: 'Vertically opposite angles are equal.',
    wrong_answer_rationale: {
      '85Â°': 'Added 20 degrees by mistake.',
      '115Â°': 'Confused with angles on a straight line.',
      '125Â°': 'Added instead of keeping equal.',
    },
    accessibility_text: 'Crossing lines with one angle labelled 65 degrees.',
  },
  {
    id: 'Q11',
    difficulty: 'Mild',
    topic: 'triangle_angles',
    question_text: 'A triangle has angles 35Â° and 70Â°. What is the third angle?',
    diagram_description: 'Triangle with two angles labelled 35Â° and 70Â°.',
    options: ['65Â°', '75Â°', '85Â°', '95Â°'],
    correct_answer: '75Â°',
    explanation: 'Angles in a triangle add to 180Â°. 180 - 35 - 70 = 75.',
    wrong_answer_rationale: {
      '65Â°': 'Subtracted only one angle.',
      '85Â°': 'Subtracted incorrectly.',
      '95Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Triangle with 35 degrees and 70 degrees marked.',
  },
  {
    id: 'Q12',
    difficulty: 'Mild',
    topic: 'straight_line',
    question_text: 'On a straight line, one angle is 125Â°. What is the other?',
    diagram_description: 'Straight line split with one angle labelled 125Â°.',
    options: ['35Â°', '45Â°', '55Â°', '65Â°'],
    correct_answer: '55Â°',
    explanation: 'Angles on a straight line add to 180Â°. 180 - 125 = 55.',
    wrong_answer_rationale: {
      '35Â°': 'Subtracted from 160.',
      '45Â°': 'Subtracted incorrectly.',
      '65Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Straight line with one angle labelled 125 degrees.',
  },
  {
    id: 'Q13',
    difficulty: 'Mild',
    topic: 'around_point',
    question_text: 'Three angles around a point are 120Â°, 80Â° and ___. What is missing?',
    diagram_description: 'Three angles around a point, two labelled 120Â° and 80Â°.',
    options: ['140Â°', '150Â°', '160Â°', '180Â°'],
    correct_answer: '160Â°',
    explanation: 'Angles around a point add to 360Â°. 360 - 120 - 80 = 160.',
    wrong_answer_rationale: {
      '140Â°': 'Subtracted incorrectly.',
      '150Â°': 'Subtracted incorrectly.',
      '180Â°': 'Confused with straight line total.',
    },
    accessibility_text: 'Point with two angles labelled 120 and 80 degrees.',
  },
  {
    id: 'Q14',
    difficulty: 'Mild',
    topic: 'isosceles',
    question_text: 'An isosceles triangle has a vertex angle of 50Â°. What is each base angle?',
    diagram_description: 'Isosceles triangle with the top angle labelled 50Â°.',
    options: ['50Â°', '55Â°', '65Â°', '70Â°'],
    correct_answer: '65Â°',
    explanation: 'Remaining total is 130Â°. Split equally: 130 Ã· 2 = 65.',
    wrong_answer_rationale: {
      '50Â°': 'Assumed all angles equal.',
      '55Â°': 'Divided incorrectly.',
      '70Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Isosceles triangle with top angle 50 degrees.',
  },
  {
    id: 'Q15',
    difficulty: 'Mild',
    topic: 'vertically_opposite',
    question_text: 'Two lines cross. One angle is 130Â°. What is the vertically opposite angle?',
    diagram_description: 'Crossing lines with one angle labelled 130Â°.',
    options: ['50Â°', '130Â°', '230Â°', '310Â°'],
    correct_answer: '130Â°',
    explanation: 'Vertically opposite angles are equal.',
    wrong_answer_rationale: {
      '50Â°': 'Confused with angles on a straight line.',
      '230Â°': 'Added instead of keeping equal.',
      '310Â°': 'Confused with full turn.',
    },
    accessibility_text: 'Crossing lines with one angle labelled 130 degrees.',
  },
  {
    id: 'Q16',
    difficulty: 'Mild',
    topic: 'right_angles',
    question_text: 'A right angle is turned 30Â° more. What is the new angle?',
    diagram_description: 'Right angle with an extra 30 degrees added.',
    options: ['90Â°', '100Â°', '120Â°', '130Â°'],
    correct_answer: '120Â°',
    explanation: '90Â° + 30Â° = 120Â°.',
    wrong_answer_rationale: {
      '90Â°': 'Forgot to add 30Â°.',
      '100Â°': 'Added only 10Â°.',
      '130Â°': 'Added 40Â° by mistake.',
    },
    accessibility_text: 'Right angle with an extra 30 degrees added.',
  },
  {
    id: 'Q17',
    difficulty: 'Mild',
    topic: 'quadrilateral',
    question_text: 'A quadrilateral has angles 80Â°, 95Â°, and 105Â°. What is the fourth angle?',
    diagram_description: 'Quadrilateral with three angles labelled 80Â°, 95Â°, 105Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '80Â°',
    explanation: 'Angles in a quadrilateral add to 360Â°. 360 - 80 - 95 - 105 = 80.',
    wrong_answer_rationale: {
      '60Â°': 'Subtracted incorrectly.',
      '70Â°': 'Subtracted incorrectly.',
      '90Â°': 'Guessed a right angle.',
    },
    accessibility_text: 'Quadrilateral with three angles labelled 80, 95, 105 degrees.',
  },
  {
    id: 'Q18',
    difficulty: 'Mild',
    topic: 'parallel_lines',
    question_text: 'Two parallel lines are cut by a transversal. One corresponding angle is 70Â°. What is the matching angle?',
    diagram_description: 'Parallel lines with a transversal and one angle labelled 70Â°.',
    options: ['70Â°', '110Â°', '140Â°', '180Â°'],
    correct_answer: '70Â°',
    explanation: 'Corresponding angles are equal on parallel lines.',
    wrong_answer_rationale: {
      '110Â°': 'Used co-interior instead of corresponding.',
      '140Â°': 'Added instead of matching.',
      '180Â°': 'Confused with a straight line.',
    },
    accessibility_text: 'Parallel lines with a transversal and a 70 degree angle.',
  },
  {
    id: 'Q19',
    difficulty: 'Mild',
    topic: 'parallel_lines',
    question_text: 'Two parallel lines are cut by a transversal. An alternate angle is 55Â°. What is the matching alternate angle?',
    diagram_description: 'Parallel lines with a transversal and one alternate angle labelled 55Â°.',
    options: ['55Â°', '125Â°', '145Â°', '235Â°'],
    correct_answer: '55Â°',
    explanation: 'Alternate angles are equal when lines are parallel.',
    wrong_answer_rationale: {
      '125Â°': 'Added 70Â° by mistake.',
      '145Â°': 'Confused with co-interior.',
      '235Â°': 'Added a full turn.',
    },
    accessibility_text: 'Parallel lines with a transversal and a 55 degree alternate angle.',
  },
  {
    id: 'Q20',
    difficulty: 'Mild',
    topic: 'word_problem',
    question_text: 'A compass turns from East to South. How many degrees is the turn?',
    diagram_description: 'Compass with an arrow turning from East to South.',
    options: ['45Â°', '90Â°', '135Â°', '180Â°'],
    correct_answer: '90Â°',
    explanation: 'East to South is a quarter turn: 90Â°.',
    wrong_answer_rationale: {
      '45Â°': 'Half of a quarter turn.',
      '135Â°': 'Three eighths of a turn.',
      '180Â°': 'Half turn.',
    },
    accessibility_text: 'Compass arrow turning from East to South.',
  },
  {
    id: 'Q21',
    difficulty: 'Medium',
    topic: 'triangle_angles',
    question_text: 'A triangle has angles 25Â° and 80Â°. What is the third angle?',
    diagram_description: 'Triangle with two angles labelled 25Â° and 80Â°.',
    options: ['65Â°', '75Â°', '85Â°', '95Â°'],
    correct_answer: '75Â°',
    explanation: '180 - 25 - 80 = 75.',
    wrong_answer_rationale: {
      '65Â°': 'Subtracted incorrectly.',
      '85Â°': 'Added instead of subtracting.',
      '95Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Triangle with 25 degrees and 80 degrees marked.',
  },
  {
    id: 'Q22',
    difficulty: 'Medium',
    topic: 'parallel_lines',
    question_text: 'Two parallel lines are cut by a transversal. One co-interior angle is 115Â°. What is the other co-interior angle?',
    diagram_description: 'Parallel lines with co-interior angle labelled 115Â°.',
    options: ['55Â°', '65Â°', '115Â°', '245Â°'],
    correct_answer: '65Â°',
    explanation: 'Co-interior angles add to 180Â°. 180 - 115 = 65.',
    wrong_answer_rationale: {
      '55Â°': 'Subtracted incorrectly.',
      '115Â°': 'Assumed equal like corresponding.',
      '245Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Parallel lines with co-interior angle labelled 115 degrees.',
  },
  {
    id: 'Q23',
    difficulty: 'Medium',
    topic: 'around_point',
    question_text: 'Angles around a point are 90Â°, 110Â°, 80Â° and ___. What is missing?',
    diagram_description: 'Point with three angles labelled 90Â°, 110Â°, 80Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '80Â°',
    explanation: '360 - 90 - 110 - 80 = 80.',
    wrong_answer_rationale: {
      '60Â°': 'Subtracted incorrectly.',
      '70Â°': 'Subtracted incorrectly.',
      '90Â°': 'Confused with right angle.',
    },
    accessibility_text: 'Point with three angles labelled 90, 110, 80 degrees.',
  },
  {
    id: 'Q24',
    difficulty: 'Medium',
    topic: 'quadrilateral',
    question_text: 'A quadrilateral has angles 100Â°, 90Â° and 85Â°. What is the fourth angle?',
    diagram_description: 'Quadrilateral with three angles labelled 100Â°, 90Â°, 85Â°.',
    options: ['65Â°', '75Â°', '85Â°', '95Â°'],
    correct_answer: '85Â°',
    explanation: '360 - 100 - 90 - 85 = 85.',
    wrong_answer_rationale: {
      '65Â°': 'Subtracted incorrectly.',
      '75Â°': 'Subtracted incorrectly.',
      '95Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Quadrilateral with three angles labelled 100, 90, 85 degrees.',
  },
  {
    id: 'Q25',
    difficulty: 'Medium',
    topic: 'isosceles',
    question_text: 'An isosceles triangle has base angles of 55Â°. What is the vertex angle?',
    diagram_description: 'Isosceles triangle with two base angles labelled 55Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '70Â°',
    explanation: 'Two base angles total 110Â°. 180 - 110 = 70.',
    wrong_answer_rationale: {
      '60Â°': 'Subtracted incorrectly.',
      '80Â°': 'Added instead of subtracting.',
      '90Â°': 'Assumed right angle.',
    },
    accessibility_text: 'Isosceles triangle with base angles 55 degrees.',
  },
  {
    id: 'Q26',
    difficulty: 'Medium',
    topic: 'word_problem',
    question_text: 'A door opens from closed to a straight line. What angle did it turn?',
    diagram_description: 'Door opening from closed to straight line.',
    options: ['90Â°', '135Â°', '180Â°', '270Â°'],
    correct_answer: '180Â°',
    explanation: 'A straight line is 180Â°.',
    wrong_answer_rationale: {
      '90Â°': 'Quarter turn.',
      '135Â°': 'Three-eighths turn.',
      '270Â°': 'Three-quarter turn.',
    },
    accessibility_text: 'Door opening to a straight line position.',
  },
  {
    id: 'Q27',
    difficulty: 'Medium',
    topic: 'vertically_opposite',
    question_text: 'Two lines cross. One angle is 40Â°. What is the angle next to it on the straight line?',
    diagram_description: 'Crossing lines with one angle labelled 40Â°.',
    options: ['40Â°', '60Â°', '140Â°', '220Â°'],
    correct_answer: '140Â°',
    explanation: 'Adjacent angles on a straight line add to 180Â°. 180 - 40 = 140.',
    wrong_answer_rationale: {
      '40Â°': 'Used vertically opposite instead of adjacent.',
      '60Â°': 'Subtracted incorrectly.',
      '220Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Crossing lines with an adjacent angle to 40 degrees.',
  },
  {
    id: 'Q28',
    difficulty: 'Medium',
    topic: 'parallel_lines',
    question_text: 'Two parallel lines are cut by a transversal. A corresponding angle is 118Â°. What is the co-interior angle on the same side?',
    diagram_description: 'Parallel lines with a corresponding angle labelled 118Â°.',
    options: ['62Â°', '118Â°', '148Â°', '242Â°'],
    correct_answer: '62Â°',
    explanation: 'Co-interior angles add to 180Â°. 180 - 118 = 62.',
    wrong_answer_rationale: {
      '118Â°': 'Used corresponding instead of co-interior.',
      '148Â°': 'Subtracted incorrectly.',
      '242Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Parallel lines with one corresponding angle 118 degrees.',
  },
  {
    id: 'Q29',
    difficulty: 'Medium',
    topic: 'turns',
    question_text: 'A robot turns three-quarters of a full turn. How many degrees is that?',
    diagram_description: 'Robot arrow showing three-quarter rotation.',
    options: ['90Â°', '180Â°', '270Â°', '360Â°'],
    correct_answer: '270Â°',
    explanation: 'Three-quarters of 360Â° is 270Â°.',
    wrong_answer_rationale: {
      '90Â°': 'One quarter turn.',
      '180Â°': 'Half turn.',
      '360Â°': 'Full turn.',
    },
    accessibility_text: 'Arrow showing three-quarter turn.',
  },
  {
    id: 'Q30',
    difficulty: 'Medium',
    topic: 'multi_step',
    question_text: 'A triangle has one right angle and one angle of 35Â°. What is the third angle?',
    diagram_description: 'Right triangle with another angle labelled 35Â°.',
    options: ['45Â°', '55Â°', '65Â°', '75Â°'],
    correct_answer: '55Â°',
    explanation: '180 - 90 - 35 = 55.',
    wrong_answer_rationale: {
      '45Â°': 'Subtracted incorrectly.',
      '65Â°': 'Added instead of subtracting.',
      '75Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Right triangle with another angle of 35 degrees.',
  },
  {
    id: 'Q31',
    difficulty: 'Hard',
    topic: 'parallel_lines',
    question_text: 'Two parallel lines are cut by a transversal. One angle is 38Â° and is alternate to angle x. What is x?',
    diagram_description: 'Parallel lines with a transversal and one alternate angle 38Â°.',
    options: ['38Â°', '52Â°', '142Â°', '180Â°'],
    correct_answer: '38Â°',
    explanation: 'Alternate angles are equal when lines are parallel.',
    wrong_answer_rationale: {
      '52Â°': 'Added 14 degrees by mistake.',
      '142Â°': 'Used co-interior instead of alternate.',
      '180Â°': 'Used straight line total.',
    },
    accessibility_text: 'Parallel lines with a transversal and alternate angle 38 degrees.',
  },
  {
    id: 'Q32',
    difficulty: 'Hard',
    topic: 'quadrilateral',
    question_text: 'A quadrilateral has three equal angles of 95Â°. What is the fourth angle?',
    diagram_description: 'Quadrilateral with three angles labelled 95Â°.',
    options: ['55Â°', '65Â°', '75Â°', '85Â°'],
    correct_answer: '75Â°',
    explanation: 'Total is 360Â°. 360 - 95 - 95 - 95 = 75.',
    wrong_answer_rationale: {
      '55Â°': 'Subtracted incorrectly.',
      '65Â°': 'Subtracted incorrectly.',
      '85Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Quadrilateral with three angles of 95 degrees.',
  },
  {
    id: 'Q33',
    difficulty: 'Hard',
    topic: 'triangle_angles',
    question_text: 'A triangle has angles in the ratio 2:3:4. What is the largest angle?',
    diagram_description: 'Triangle with angles labelled 2x, 3x, 4x.',
    options: ['60Â°', '80Â°', '90Â°', '100Â°'],
    correct_answer: '80Â°',
    explanation: 'Total parts = 9. 180 Ã· 9 = 20. Largest = 4 Ã— 20 = 80.',
    wrong_answer_rationale: {
      '60Â°': 'Used 3x instead of 4x.',
      '90Â°': 'Assumed right angle.',
      '100Â°': 'Multiplied by 5 instead of 4.',
    },
    accessibility_text: 'Triangle with angles marked 2x, 3x, 4x.',
  },
  {
    id: 'Q34',
    difficulty: 'Hard',
    topic: 'parallel_lines',
    question_text: 'Parallel lines are cut by a transversal. One co-interior angle is 132Â°. What is the corresponding angle on the other line?',
    diagram_description: 'Parallel lines with co-interior angle 132Â°.',
    options: ['48Â°', '132Â°', '168Â°', '228Â°'],
    correct_answer: '48Â°',
    explanation: 'Co-interior adds to 180Â°, so the matching corresponding angle is 180 - 132 = 48Â°.',
    wrong_answer_rationale: {
      '132Â°': 'Used co-interior instead of corresponding.',
      '168Â°': 'Subtracted incorrectly.',
      '228Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Parallel lines with co-interior angle 132 degrees.',
  },
  {
    id: 'Q35',
    difficulty: 'Hard',
    topic: 'multi_step',
    question_text: 'Angles around a point are 90Â°, 140Â°, and 70Â°. What is the final angle?',
    diagram_description: 'Point with three angles labelled 90Â°, 140Â°, 70Â°.',
    options: ['40Â°', '50Â°', '60Â°', '70Â°'],
    correct_answer: '60Â°',
    explanation: '360 - 90 - 140 - 70 = 60.',
    wrong_answer_rationale: {
      '40Â°': 'Subtracted incorrectly.',
      '50Â°': 'Subtracted incorrectly.',
      '70Â°': 'Confused with one given angle.',
    },
    accessibility_text: 'Point with three angles labelled 90, 140, 70 degrees.',
  },
  {
    id: 'Q36',
    difficulty: 'Hard',
    topic: 'isosceles',
    question_text: 'An isosceles triangle has a vertex angle of 30Â°. What are the base angles?',
    diagram_description: 'Isosceles triangle with top angle labelled 30Â°.',
    options: ['60Â°', '70Â°', '75Â°', '85Â°'],
    correct_answer: '75Â°',
    explanation: 'Remaining total is 150Â°. 150 Ã· 2 = 75.',
    wrong_answer_rationale: {
      '60Â°': 'Divided 120 instead of 150.',
      '70Â°': 'Divided incorrectly.',
      '85Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Isosceles triangle with top angle 30 degrees.',
  },
  {
    id: 'Q37',
    difficulty: 'Hard',
    topic: 'parallel_lines',
    question_text: 'A transversal cuts parallel lines. An alternate angle is 72Â°. What is the adjacent angle on the straight line?',
    diagram_description: 'Parallel lines with alternate angle 72Â°.',
    options: ['72Â°', '98Â°', '108Â°', '128Â°'],
    correct_answer: '108Â°',
    explanation: 'Adjacent on a straight line: 180 - 72 = 108.',
    wrong_answer_rationale: {
      '72Â°': 'Stayed with alternate angle.',
      '98Â°': 'Subtracted incorrectly.',
      '128Â°': 'Subtracted incorrectly.',
    },
    accessibility_text: 'Parallel lines with alternate angle 72 degrees.',
  },
  {
    id: 'Q38',
    difficulty: 'Hard',
    topic: 'word_problem',
    question_text: 'A lighthouse beam turns from North to South-West. How many degrees does it turn?',
    diagram_description: 'Compass showing turn from North to South-West.',
    options: ['90Â°', '135Â°', '180Â°', '225Â°'],
    correct_answer: '225Â°',
    explanation: 'North to West is 270Â°; to South-West is 225Â°.',
    wrong_answer_rationale: {
      '90Â°': 'Quarter turn.',
      '135Â°': 'Three-eighths turn.',
      '180Â°': 'Half turn.',
    },
    accessibility_text: 'Compass showing a turn from North to South-West.',
  },
  {
    id: 'Q39',
    difficulty: 'Hard',
    topic: 'multi_step',
    question_text: 'A triangle has one angle of 120Â°. The other two angles are equal. What is each?',
    diagram_description: 'Triangle with one angle labelled 120Â° and two equal angles.',
    options: ['20Â°', '30Â°', '40Â°', '50Â°'],
    correct_answer: '30Â°',
    explanation: 'Remaining total is 60Â°. Split equally: 60 Ã· 2 = 30.',
    wrong_answer_rationale: {
      '20Â°': 'Divided 40 instead of 60.',
      '40Â°': 'Subtracted incorrectly.',
      '50Â°': 'Guessed.',
    },
    accessibility_text: 'Triangle with one angle 120 degrees and two equal angles.',
  },
  {
    id: 'Q40',
    difficulty: 'Hard',
    topic: 'parallel_lines',
    question_text: 'Parallel lines are cut by a transversal. A corresponding angle is 146Â°. What is the interior angle on the same side?',
    diagram_description: 'Parallel lines with corresponding angle 146Â°.',
    options: ['34Â°', '46Â°', '146Â°', '214Â°'],
    correct_answer: '34Â°',
    explanation: 'Co-interior angles total 180Â°. 180 - 146 = 34.',
    wrong_answer_rationale: {
      '46Â°': 'Subtracted incorrectly.',
      '146Â°': 'Stayed with corresponding angle.',
      '214Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Parallel lines with corresponding angle 146 degrees.',
  },
  {
    id: 'Q41',
    difficulty: 'Expert',
    topic: 'multi_step',
    question_text: 'A triangle has angles in the ratio 1:2:3. What is the smallest angle?',
    diagram_description: 'Triangle with angles labelled 1x, 2x, 3x.',
    options: ['20Â°', '30Â°', '40Â°', '50Â°'],
    correct_answer: '30Â°',
    explanation: 'Total parts 6. 180 Ã· 6 = 30. Smallest is 1 Ã— 30.',
    wrong_answer_rationale: {
      '20Â°': 'Divided 180 by 9 instead of 6.',
      '40Â°': 'Used 2x instead of 1x.',
      '50Â°': 'Guessed without using ratios.',
    },
    accessibility_text: 'Triangle with angles marked 1x, 2x, 3x.',
  },
  {
    id: 'Q42',
    difficulty: 'Expert',
    topic: 'straight_line',
    question_text: 'Two angles on a straight line are in the ratio 1:2. What is the smaller angle?',
    diagram_description: 'Straight line split into two angles labelled 1x and 2x.',
    options: ['50Â°', '60Â°', '70Â°', '80Â°'],
    correct_answer: '60Â°',
    explanation: 'Total parts 3. 180 Ã· 3 = 60. Smaller angle is 60Â°.',
    wrong_answer_rationale: {
      '50Â°': 'Divided 180 by 4.',
      '70Â°': 'Added instead of dividing.',
      '80Â°': 'Guessed.',
    },
    accessibility_text: 'Straight line split into angles 1x and 2x.',
  },
  {
    id: 'Q43',
    difficulty: 'Expert',
    topic: 'quadrilateral',
    question_text: 'A quadrilateral has angles 90Â°, 110Â°, x and x. What is x?',
    diagram_description: 'Quadrilateral with angles 90Â°, 110Â° and two equal angles marked x.',
    options: ['70Â°', '80Â°', '90Â°', '100Â°'],
    correct_answer: '80Â°',
    explanation: 'Total is 360Â°. 360 - 90 - 110 = 160. Split equally gives 80Â°.',
    wrong_answer_rationale: {
      '70Â°': 'Subtracted incorrectly.',
      '90Â°': 'Assumed right angle.',
      '100Â°': 'Added instead of splitting equally.',
    },
    accessibility_text: 'Quadrilateral with angles 90 degrees, 110 degrees, and two equal angles.',
  },
  {
    id: 'Q44',
    difficulty: 'Expert',
    topic: 'around_point',
    question_text: 'Angles around a point are in the ratio 2:3:5. What is the largest angle?',
    diagram_description: 'Point with angles labelled 2x, 3x and 5x.',
    options: ['144Â°', '180Â°', '216Â°', '240Â°'],
    correct_answer: '180Â°',
    explanation: 'Total parts 10. 360 Ã· 10 = 36. Largest is 5 Ã— 36 = 180.',
    wrong_answer_rationale: {
      '144Â°': 'Used 4x instead of 5x.',
      '216Â°': 'Used 6x instead of 5x.',
      '240Â°': 'Used 6.5x instead of 5x.',
    },
    accessibility_text: 'Point with angles marked 2x, 3x, 5x.',
  },
  {
    id: 'Q45',
    difficulty: 'Expert',
    topic: 'isosceles',
    question_text: 'An isosceles triangle has a vertex angle of 40Â°. What is each base angle?',
    diagram_description: 'Isosceles triangle with top angle labelled 40Â°.',
    options: ['60Â°', '70Â°', '80Â°', '90Â°'],
    correct_answer: '70Â°',
    explanation: 'Remaining total is 140Â°. 140 Ã· 2 = 70.',
    wrong_answer_rationale: {
      '60Â°': 'Divided 120 instead of 140.',
      '80Â°': 'Subtracted incorrectly.',
      '90Â°': 'Assumed right angle.',
    },
    accessibility_text: 'Isosceles triangle with top angle 40 degrees.',
  },
  {
    id: 'Q46',
    difficulty: 'Expert',
    topic: 'parallel_lines',
    question_text: 'Parallel lines are cut by a transversal. An interior angle is 128Â°. What is the co-interior angle on the same side?',
    diagram_description: 'Parallel lines with an interior angle labelled 128Â°.',
    options: ['42Â°', '52Â°', '128Â°', '180Â°'],
    correct_answer: '52Â°',
    explanation: 'Co-interior angles add to 180Â°. 180 - 128 = 52.',
    wrong_answer_rationale: {
      '42Â°': 'Subtracted incorrectly.',
      '128Â°': 'Assumed equal instead of supplementary.',
      '180Â°': 'Used straight line total only.',
    },
    accessibility_text: 'Parallel lines with an interior angle 128 degrees.',
  },
  {
    id: 'Q47',
    difficulty: 'Expert',
    topic: 'word_problem',
    question_text: 'A robot turns a right angle, then another 45Â°. What is the total turn?',
    diagram_description: 'Robot arrow showing a 90Â° turn then 45Â° more.',
    options: ['120Â°', '135Â°', '150Â°', '180Â°'],
    correct_answer: '135Â°',
    explanation: '90Â° + 45Â° = 135Â°.',
    wrong_answer_rationale: {
      '120Â°': 'Added only 30Â°.',
      '150Â°': 'Added 60Â° instead of 45Â°.',
      '180Â°': 'Rounded to a half turn.',
    },
    accessibility_text: 'Arrow showing a 90 degree turn then 45 degrees more.',
  },
  {
    id: 'Q48',
    difficulty: 'Expert',
    topic: 'triangle_angles',
    question_text: 'A triangle has angles 2x, 2x and x. What is x?',
    diagram_description: 'Triangle with angles labelled 2x, 2x and x.',
    options: ['30Â°', '36Â°', '40Â°', '45Â°'],
    correct_answer: '36Â°',
    explanation: 'Total parts 5. 180 Ã· 5 = 36.',
    wrong_answer_rationale: {
      '30Â°': 'Divided by 6 instead of 5.',
      '40Â°': 'Used 200 Ã· 5.',
      '45Â°': 'Guessed.',
    },
    accessibility_text: 'Triangle with angles marked 2x, 2x and x.',
  },
  {
    id: 'Q49',
    difficulty: 'Expert',
    topic: 'vertically_opposite',
    question_text: 'Two lines cross. One angle is 150Â°. What is the adjacent angle on the straight line?',
    diagram_description: 'Crossing lines with one angle labelled 150Â°.',
    options: ['30Â°', '40Â°', '150Â°', '210Â°'],
    correct_answer: '30Â°',
    explanation: 'Adjacent angles on a straight line add to 180Â°. 180 - 150 = 30.',
    wrong_answer_rationale: {
      '40Â°': 'Subtracted incorrectly.',
      '150Â°': 'Used vertically opposite instead of adjacent.',
      '210Â°': 'Added instead of subtracting.',
    },
    accessibility_text: 'Crossing lines with one angle labelled 150 degrees.',
  },
  {
    id: 'Q50',
    difficulty: 'Expert',
    topic: 'quadrilateral',
    question_text: 'A quadrilateral has angles in the ratio 1:1:2:2. What is the largest angle?',
    diagram_description: 'Quadrilateral with angles labelled 1x, 1x, 2x, 2x.',
    options: ['90Â°', '100Â°', '120Â°', '150Â°'],
    correct_answer: '120Â°',
    explanation: 'Total parts 6. 360 Ã· 6 = 60. Largest is 2 Ã— 60 = 120.',
    wrong_answer_rationale: {
      '90Â°': 'Used 1.5x instead of 2x.',
      '100Â°': 'Added 40 instead of 60.',
      '150Â°': 'Used 2.5x instead of 2x.',
    },
    accessibility_text: 'Quadrilateral with angles marked 1x, 1x, 2x, 2x.',
  },
];

export const buildAngleQuestions = ({ launcherX, groundY, gravity }: BuildConfig): AngleQuestion[] => {
  const speed = 520;
  return questionBank.map((entry, index) =>
    toAngleQuestion(entry, index, speed, launcherX, groundY, gravity, 54),
  );
};


