export type MiniGameRole =
  | 'concept_visualisation'
  | 'fluency'
  | 'strategy'
  | 'pressure_timing'
  | 'application'
  | 'mixed_mastery';

export interface MiniGameBlueprint {
  key: string;
  name: string;
  role: MiniGameRole;
  curriculumObjectives: string[];
  questionTypes: string[];
  difficultyCurve: string;
  failureState: string;
  replayValue: string;
}

export interface IslandBlueprint {
  id: number;
  name: string;
  domain: string;
  purpose: string;
  miniGames: MiniGameBlueprint[];
}

export const ISLAND_BLUEPRINTS: IslandBlueprint[] = [
  {
    id: 1,
    name: 'Number Base Camp',
    domain: 'Number',
    purpose: 'Foundational number confidence and speed.',
    miniGames: [
      {
        key: 'place_value_panic',
        name: 'Place Value Panic',
        role: 'concept_visualisation',
        curriculumObjectives: ['place_value', 'digit_value'],
        questionTypes: ['column placement', 'value identification'],
        difficultyCurve: 'larger values, then decimals',
        failureState: 'queue overflow',
        replayValue: 'randomised digit sets',
      },
      {
        key: 'number_line_ninja',
        name: 'Number Line Ninja',
        role: 'application',
        curriculumObjectives: ['compare_order', 'negative_numbers'],
        questionTypes: ['land on value', 'interval steps'],
        difficultyCurve: 'wider ranges and tighter timing',
        failureState: 'missed targets',
        replayValue: 'dynamic range generation',
      },
      {
        key: 'prime_pop',
        name: 'Prime Pop',
        role: 'pressure_timing',
        curriculumObjectives: ['prime_numbers', 'factors_multiples'],
        questionTypes: ['prime selection', 'composite traps'],
        difficultyCurve: 'faster waves and trick values',
        failureState: 'wrong hit streak',
        replayValue: 'procedural target waves',
      },
      {
        key: 'rounding_rampage',
        name: 'Rounding Rampage',
        role: 'fluency',
        curriculumObjectives: ['rounding_10_100_1000'],
        questionTypes: ['round to target place'],
        difficultyCurve: 'mixed place values under pressure',
        failureState: 'wrong gate routing',
        replayValue: 'variable gate layouts',
      },
      {
        key: 'calculation_clash',
        name: 'Calculation Clash',
        role: 'pressure_timing',
        curriculumObjectives: ['basic_arithmetic_fluency'],
        questionTypes: ['rapid operations'],
        difficultyCurve: 'faster and multi-step rounds',
        failureState: 'timer out',
        replayValue: 'high-score chasing',
      },
      {
        key: 'factor_frenzy',
        name: 'Factor Frenzy',
        role: 'mixed_mastery',
        curriculumObjectives: ['factors', 'multiples', 'divisibility'],
        questionTypes: ['common factors', 'divisible checks'],
        difficultyCurve: 'multi-condition filtering',
        failureState: 'error threshold',
        replayValue: 'rotating rule sets',
      },
    ],
  },
  {
    id: 2,
    name: 'Fraction Lagoon',
    domain: 'Fractions and FDP',
    purpose: 'Fractions as composable, visual gameplay.',
    miniGames: [
      {
        key: 'take_out_rush',
        name: 'Take-Out Rush',
        role: 'concept_visualisation',
        curriculumObjectives: ['equivalent_fractions', 'fraction_addition'],
        questionTypes: ['compose target fraction'],
        difficultyCurve: 'blocked pieces and tighter patience',
        failureState: 'overfill or timeout',
        replayValue: 'multiple valid compositions',
      },
      {
        key: 'fraction_forge',
        name: 'Fraction Forge',
        role: 'application',
        curriculumObjectives: ['add_subtract_fractions'],
        questionTypes: ['exact total crafting'],
        difficultyCurve: 'alternative combinations required',
        failureState: 'target mismatch',
        replayValue: 'varied target sets',
      },
      {
        key: 'match3_equivalence',
        name: 'Match-3 Equivalence',
        role: 'pressure_timing',
        curriculumObjectives: ['fraction_decimal_percent_equivalence'],
        questionTypes: ['equivalent value matching'],
        difficultyCurve: 'higher board complexity',
        failureState: 'move starvation',
        replayValue: 'board randomisation',
      },
      {
        key: 'fraction_flow',
        name: 'Fraction Flow',
        role: 'strategy',
        curriculumObjectives: ['compare_fractions', 'ordering'],
        questionTypes: ['sort low-to-high'],
        difficultyCurve: 'mixed form values',
        failureState: 'ordering errors',
        replayValue: 'dynamic stream values',
      },
      {
        key: 'fraction_of_amount',
        name: 'Fraction of Amount',
        role: 'application',
        curriculumObjectives: ['fractions_of_quantities'],
        questionTypes: ['find part of set'],
        difficultyCurve: 'larger sets and multi-step',
        failureState: 'incorrect allocation',
        replayValue: 'varied quantity targets',
      },
      {
        key: 'simplify_sprint',
        name: 'Simplify Sprint',
        role: 'fluency',
        curriculumObjectives: ['simplifying_fractions', 'common_factors'],
        questionTypes: ['reduce to simplest form'],
        difficultyCurve: 'faster simplification rounds',
        failureState: 'timer out',
        replayValue: 'broad fraction pool',
      },
    ],
  },
  {
    id: 3,
    name: 'Operations Outpost',
    domain: 'Arithmetic Methods',
    purpose: 'Secure arithmetic methods and multi-step control.',
    miniGames: [
      {
        key: 'calculation_clash_advanced',
        name: 'Calculation Clash Advanced',
        role: 'pressure_timing',
        curriculumObjectives: ['mixed_operations'],
        questionTypes: ['rapid mixed arithmetic'],
        difficultyCurve: 'higher pace and complexity',
        failureState: 'timer out',
        replayValue: 'combo optimisation',
      },
      {
        key: 'multiplication_mine',
        name: 'Multiplication Mine',
        role: 'fluency',
        curriculumObjectives: ['multiplication', 'long_multiplication'],
        questionTypes: ['product selection'],
        difficultyCurve: 'larger factors',
        failureState: 'path collapse',
        replayValue: 'procedural routes',
      },
      {
        key: 'division_dock',
        name: 'Division Dock',
        role: 'application',
        curriculumObjectives: ['division', 'long_division'],
        questionTypes: ['quotients and grouping'],
        difficultyCurve: 'remainders and larger values',
        failureState: 'dispatch errors',
        replayValue: 'rotating cargo sets',
      },
      {
        key: 'order_ops_arena',
        name: 'Order Ops Arena',
        role: 'strategy',
        curriculumObjectives: ['order_of_operations'],
        questionTypes: ['expression sequencing'],
        difficultyCurve: 'nested expressions',
        failureState: 'sequence mistakes',
        replayValue: 'expression variations',
      },
      {
        key: 'arithmetic_gauntlet',
        name: 'Arithmetic Gauntlet',
        role: 'mixed_mastery',
        curriculumObjectives: ['multi_step_arithmetic'],
        questionTypes: ['linked calculations'],
        difficultyCurve: 'longer chains',
        failureState: 'health depletion',
        replayValue: 'survival scoring',
      },
      {
        key: 'remainder_run',
        name: 'Remainder Run',
        role: 'application',
        curriculumObjectives: ['division_interpretation', 'remainders'],
        questionTypes: ['route by quotient/remainder'],
        difficultyCurve: 'stricter conditions',
        failureState: 'wrong route',
        replayValue: 'variable remainder goals',
      },
    ],
  },
  {
    id: 4,
    name: 'Ratio Reef',
    domain: 'Ratio and Proportion',
    purpose: 'Build strong proportional reasoning through system gameplay.',
    miniGames: [
      {
        key: 'potion_panic',
        name: 'Potion Panic',
        role: 'concept_visualisation',
        curriculumObjectives: ['ratio_language', 'proportion'],
        questionTypes: ['mix to ratio target'],
        difficultyCurve: 'faster fills with constraints',
        failureState: 'ratio mismatch',
        replayValue: 'recipe variation',
      },
      {
        key: 'ratio_recipes',
        name: 'Ratio Recipes',
        role: 'application',
        curriculumObjectives: ['scale_up_down'],
        questionTypes: ['scaled ingredients'],
        difficultyCurve: 'larger scale factors',
        failureState: 'incorrect scale conversion',
        replayValue: 'dynamic recipe cards',
      },
      {
        key: 'share_splitter',
        name: 'Share Splitter',
        role: 'strategy',
        curriculumObjectives: ['sharing_in_ratio'],
        questionTypes: ['resource allocation'],
        difficultyCurve: 'higher totals and uneven splits',
        failureState: 'allocation error',
        replayValue: 'procedural share sets',
      },
      {
        key: 'proportion_puzzle',
        name: 'Proportion Puzzle',
        role: 'mixed_mastery',
        curriculumObjectives: ['equivalent_ratio'],
        questionTypes: ['missing proportional values'],
        difficultyCurve: 'multi-step relations',
        failureState: 'logic mismatch',
        replayValue: 'generated value systems',
      },
      {
        key: 'scale_builder',
        name: 'Scale Builder',
        role: 'application',
        curriculumObjectives: ['scale_factor_reasoning'],
        questionTypes: ['resize plans'],
        difficultyCurve: 'compound scaling',
        failureState: 'incorrect dimensions',
        replayValue: 'varied build specs',
      },
      {
        key: 'ratio_rush',
        name: 'Ratio Rush',
        role: 'pressure_timing',
        curriculumObjectives: ['applied_ratio_fluency'],
        questionTypes: ['rapid ratio checks'],
        difficultyCurve: 'speed escalation',
        failureState: 'timer out',
        replayValue: 'endless challenge mode potential',
      },
    ],
  },
  {
    id: 5,
    name: 'Geometry Gorge',
    domain: 'Geometry and Position',
    purpose: 'Shape and angle fluency via movement and spatial interaction.',
    miniGames: [
      {
        key: 'angle_arena',
        name: 'Angle Arena',
        role: 'concept_visualisation',
        curriculumObjectives: ['angles'],
        questionTypes: ['target angle matching'],
        difficultyCurve: 'missing-angle integration',
        failureState: 'miss tolerance exceeded',
        replayValue: 'variable target sets',
      },
      {
        key: 'polygon_palace',
        name: 'Polygon Palace',
        role: 'fluency',
        curriculumObjectives: ['shape_properties', 'polygons'],
        questionTypes: ['classify by properties'],
        difficultyCurve: 'more subtle distinctions',
        failureState: 'classification streak break',
        replayValue: 'broad shape pools',
      },
      {
        key: 'rotation_relay',
        name: 'Rotation Relay',
        role: 'strategy',
        curriculumObjectives: ['rotation'],
        questionTypes: ['rotate to match target'],
        difficultyCurve: 'multi-turn and direction traps',
        failureState: 'misorientation',
        replayValue: 'procedural orientation targets',
      },
      {
        key: 'reflection_rescue',
        name: 'Reflection Rescue',
        role: 'application',
        curriculumObjectives: ['reflection'],
        questionTypes: ['mirror line mapping'],
        difficultyCurve: 'offset mirror lines',
        failureState: 'mirror mismatch',
        replayValue: 'dynamic grid patterns',
      },
      {
        key: 'translation_tracker',
        name: 'Translation Tracker',
        role: 'application',
        curriculumObjectives: ['translation', 'coordinates'],
        questionTypes: ['move by vector instruction'],
        difficultyCurve: 'longer movement chains',
        failureState: 'wrong final coordinate',
        replayValue: 'generated movement tasks',
      },
      {
        key: 'coordinates_quest',
        name: 'Coordinates Quest',
        role: 'mixed_mastery',
        curriculumObjectives: ['plotting_points', 'position'],
        questionTypes: ['plot/read coordinate pairs'],
        difficultyCurve: 'higher grid complexity',
        failureState: 'plotting accuracy threshold',
        replayValue: 'new coordinate maps each run',
      },
    ],
  },
  {
    id: 6,
    name: 'Measure Mountain',
    domain: 'Measurement',
    purpose: 'Practical measurement, conversion, and construction reasoning.',
    miniGames: [
      {
        key: 'time_keeper_cove',
        name: 'Time Keeper Cove',
        role: 'concept_visualisation',
        curriculumObjectives: ['time', 'elapsed_time'],
        questionTypes: ['clock setting and duration'],
        difficultyCurve: 'mixed analog/digital and intervals',
        failureState: 'dispatch delays',
        replayValue: 'rotating schedule scenarios',
      },
      {
        key: 'conversion_canyon',
        name: 'Conversion Canyon',
        role: 'fluency',
        curriculumObjectives: ['unit_conversion'],
        questionTypes: ['metric conversion'],
        difficultyCurve: 'multi-step unit jumps',
        failureState: 'conversion mismatch',
        replayValue: 'broad conversion pool',
      },
      {
        key: 'perimeter_path',
        name: 'Perimeter Path',
        role: 'application',
        curriculumObjectives: ['perimeter'],
        questionTypes: ['boundary totals'],
        difficultyCurve: 'composite shapes',
        failureState: 'incorrect length total',
        replayValue: 'generated path shapes',
      },
      {
        key: 'builder_bay',
        name: 'Builder Bay',
        role: 'concept_visualisation',
        curriculumObjectives: ['area'],
        questionTypes: ['construct to target area'],
        difficultyCurve: 'non-trivial layouts',
        failureState: 'area mismatch',
        replayValue: 'layout randomisation',
      },
      {
        key: 'volume_vault',
        name: 'Volume Vault',
        role: 'strategy',
        curriculumObjectives: ['volume'],
        questionTypes: ['cube packing'],
        difficultyCurve: 'larger cuboids with constraints',
        failureState: 'target volume miss',
        replayValue: 'variable vault dimensions',
      },
      {
        key: 'measure_mix_up',
        name: 'Measure Mix-Up',
        role: 'mixed_mastery',
        curriculumObjectives: ['measurement_reasoning'],
        questionTypes: ['mixed measure scenarios'],
        difficultyCurve: 'multi-step mixed tasks',
        failureState: 'error threshold',
        replayValue: 'mixed challenge rotations',
      },
    ],
  },
  {
    id: 7,
    name: 'Data Desert',
    domain: 'Statistics',
    purpose: 'Fast, accurate interpretation of data displays.',
    miniGames: [
      {
        key: 'data_dash',
        name: 'Data Dash',
        role: 'pressure_timing',
        curriculumObjectives: ['chart_reading'],
        questionTypes: ['pick correct lane from chart'],
        difficultyCurve: 'faster reveal windows',
        failureState: 'wrong lane streak',
        replayValue: 'generated chart values',
      },
      {
        key: 'graph_grabber',
        name: 'Graph Grabber',
        role: 'fluency',
        curriculumObjectives: ['bar_charts', 'line_graphs'],
        questionTypes: ['extract chart values'],
        difficultyCurve: 'denser charts and tighter timers',
        failureState: 'timeout',
        replayValue: 'random chart sets',
      },
      {
        key: 'table_trouble',
        name: 'Table Trouble',
        role: 'application',
        curriculumObjectives: ['table_interpretation'],
        questionTypes: ['lookup and compare'],
        difficultyCurve: 'multi-column tables',
        failureState: 'lookup errors',
        replayValue: 'procedural tables',
      },
      {
        key: 'line_graph_lab',
        name: 'Line Graph Lab',
        role: 'concept_visualisation',
        curriculumObjectives: ['line_graph_interpretation'],
        questionTypes: ['trend/value questions'],
        difficultyCurve: 'more complex trends',
        failureState: 'misread trend',
        replayValue: 'new graph patterns',
      },
      {
        key: 'chart_challenge',
        name: 'Chart Challenge',
        role: 'mixed_mastery',
        curriculumObjectives: ['multi_format_statistics'],
        questionTypes: ['identify and interpret format'],
        difficultyCurve: 'rapid format switching',
        failureState: 'accuracy drop',
        replayValue: 'mixed-format pools',
      },
      {
        key: 'data_detective',
        name: 'Data Detective',
        role: 'strategy',
        curriculumObjectives: ['data_inference'],
        questionTypes: ['comparison and inference'],
        difficultyCurve: 'multi-clue deductions',
        failureState: 'reasoning miss',
        replayValue: 'case-style puzzle sets',
      },
    ],
  },
  {
    id: 8,
    name: 'SATs Summit',
    domain: 'Mixed Reasoning',
    purpose: 'Endgame transfer across all domains under pressure.',
    miniGames: [
      {
        key: 'market_mayhem',
        name: 'Market Mayhem',
        role: 'application',
        curriculumObjectives: ['money', 'multi_step_operations'],
        questionTypes: ['shop calculation scenarios'],
        difficultyCurve: 'stacked constraints',
        failureState: 'order mismatch',
        replayValue: 'dynamic market scenarios',
      },
      {
        key: 'problem_pyramid',
        name: 'Problem Pyramid',
        role: 'strategy',
        curriculumObjectives: ['multi_step_reasoning'],
        questionTypes: ['linked-step problems'],
        difficultyCurve: 'longer chains and less scaffolding',
        failureState: 'chain break',
        replayValue: 'generated puzzle paths',
      },
      {
        key: 'mixed_mastery',
        name: 'Mixed Mastery',
        role: 'mixed_mastery',
        curriculumObjectives: ['cross_domain_recall'],
        questionTypes: ['rapid mixed rounds'],
        difficultyCurve: 'broader domain switching',
        failureState: 'accuracy threshold',
        replayValue: 'large mixed pool',
      },
      {
        key: 'strategy_survival',
        name: 'Strategy Survival',
        role: 'pressure_timing',
        curriculumObjectives: ['transfer_under_pressure'],
        questionTypes: ['mixed challenge waves'],
        difficultyCurve: 'escalating wave pressure',
        failureState: 'lives depleted',
        replayValue: 'survival scoring',
      },
      {
        key: 'timed_test_trials',
        name: 'Timed Test Trials',
        role: 'fluency',
        curriculumObjectives: ['speed_and_confidence'],
        questionTypes: ['sat-style timed sets'],
        difficultyCurve: 'tighter time budgets',
        failureState: 'time out',
        replayValue: 'new timed packs',
      },
      {
        key: 'multi_step_marathon',
        name: 'Multi-Step Marathon',
        role: 'application',
        curriculumObjectives: ['advanced_problem_solving'],
        questionTypes: ['long-form mixed reasoning'],
        difficultyCurve: 'higher complexity chains',
        failureState: 'completion failure',
        replayValue: 'scenario-driven variation',
      },
    ],
  },
];
